rm -f /etc/munin/plugins/mysql_bin_relay_log ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_bin_relay_log
rm -f /etc/munin/plugins/mysql_commands ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_commands
rm -f /etc/munin/plugins/mysql_connections ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_connections
rm -f /etc/munin/plugins/mysql_files_tables ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_files_tables
rm -f /etc/munin/plugins/mysql_innodb_bpool ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_bpool
rm -f /etc/munin/plugins/mysql_innodb_bpool_act ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_bpool_act
rm -f /etc/munin/plugins/mysql_innodb_insert_buf ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_insert_buf
rm -f /etc/munin/plugins/mysql_innodb_io ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_io
rm -f /etc/munin/plugins/mysql_innodb_io_pend ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_io_pend
rm -f /etc/munin/plugins/mysql_innodb_log ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_log
rm -f /etc/munin/plugins/mysql_innodb_rows ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_rows
rm -f /etc/munin/plugins/mysql_innodb_semaphores ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_semaphores
rm -f /etc/munin/plugins/mysql_innodb_tnx ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_innodb_tnx
rm -f /etc/munin/plugins/mysql_myisam_indexes ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_myisam_indexes
rm -f /etc/munin/plugins/mysql_network_traffic ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_network_traffic
rm -f /etc/munin/plugins/mysql_qcache ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_qcache
rm -f /etc/munin/plugins/mysql_qcache_mem ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_qcache_mem
rm -f /etc/munin/plugins/mysql_replication ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_replication
rm -f /etc/munin/plugins/mysql_select_types ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_select_types
rm -f /etc/munin/plugins/mysql_slow ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_slow
rm -f /etc/munin/plugins/mysql_sorts ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_sorts
rm -f /etc/munin/plugins/mysql_table_locks ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_table_locks
rm -f /etc/munin/plugins/mysql_tmp_tables ; ln -s /etc/munin/openquery/mysql_ /etc/munin/plugins/mysql_tmp_tables
